export const CLASSES_OPTION = [
  { label: 'Berserker', value: 'berserker' },
  { label: 'Destroyer', value: 'destroyer' },
  { label: 'Gunlancer', value: 'gunlancer' },
  { label: 'Paladin', value: 'paladin' },
  { label: 'Slayer', value: 'slayer' },
  { label: 'Arcanist', value: 'arcanist' },
  { label: 'Bard', value: 'bard' },
  { label: 'Sorceress', value: 'sorceress' },
  { label: 'Summoner', value: 'summoner' },
  { label: 'Glaivier', value: 'glaivier' },
  { label: 'Scrapper', value: 'scrapper' },
  { label: 'Soulfist', value: 'soulfist' },
  { label: 'Wardancer', value: 'wardancer' },
  { label: 'Striker', value: 'striker' },
  { label: 'Breaker', value: 'breaker' },
  { label: 'Artillerist', value: 'artillerist' },
  { label: 'Deadeye', value: 'deadeye' },
  { label: 'Gunslinger', value: 'gunslinger' },
  { label: 'Machinist', value: 'machinist' },
  { label: 'Sharpshooter', value: 'sharpshooter' },
  { label: 'Deathblade', value: 'deathblade' },
  { label: 'Reaper', value: 'reaper' },
  { label: 'Shadowhunter', value: 'shadowhunter' },
  { label: 'Souleater', value: 'souleater' },
  { label: 'Aeromancer', value: 'aeromancer' },
  { label: 'Artist', value: 'artist' },
] as const
