export const COMBAT_ENGRAVINGS = [
  'Adrenaline',
  'All-Out Attack',
  'Ambush Master',
  'Awakening',
  'Barricade',
  'Broken Bone',
  'Contender',
  'Crisis Evasion',
  'Crushing Fist',
  'Cursed Doll',
  'Disrespect',
  'Divine Protection',
  'Drops of Ether',
  'Emergency Rescue',
  'Enhanced Shield',
  'Ether Predator',
  'Expert',
  'Explosive Expert',
  'Fortitude',
  'Grudge',
  'Heavy Armor',
  'Hit Master',
  'Keen Blunt Weapon',
  'Lightning Fury',
  'Magick Stream',
  'Mass Increase',
  'Master Brawler',
  'Master of Escape',
  "Master's Tenacity",
  'Max MP Increase',
  'MP Efficiency Increase',
  'Necromancy',
  'Precise Dagger',
  'Preemptive Strike',
  'Propulsion',
  'Raid Captain',
  'Shield Piercing',
  'Sight Focus',
  'Spirit Absorption',
  'Stabilized Status',
  'Strong Will',
  'Super Charge',
  'Vital Point Hit',
] as const
