export const CLASS_ENGRAVINGS = {
  berserker: ["Berserker's Technique", 'Mayhem'],
  destroyer: ['Gravity Training', 'Rage Hammer'],
  gunlancer: ['Combat Readiness', 'Lone Knight'],
  paladin: ['Blessed Aura', 'Judgment'],
  slayer: ['Predator', 'Punisher'],
  arcanist: ["Empress's Grace", 'Order of the Emperor'],
  bard: ['Desperate Salvation', 'True Courage'],
  sorceress: ['Igniter', 'Reflux'],
  summoner: ['Master Summoner', 'Communication Overflow'],
  glaivier: ['Pinnacle', 'Control'],
  scrapper: ['Ultimate Skill: Taijutsu', 'Shock Training'],
  soulfist: ['Energy Overflow', 'Robust Spirit'],
  wardancer: ['Esoteric Skill', 'First Intention'],
  striker: ['Esoteric Flurry', 'Deathblow'],
  breaker: ["Asura's Path", 'Brawl King Storm'],
  artillerist: ['Barrage Enhancement', 'Firepower Enhancement'],
  deadeye: ['Enhanced Weapon', 'Pistoleer'],
  gunslinger: ['Peacemaker', 'Time to Hunt'],
  machinist: ['Arthetinean Skill', 'Evolutionary Legacy'],
  sharpshooter: ['Loyal Companion', 'Death Strike'],
  deathblade: ['Surge', 'Remaining Energy'],
  reaper: ['Hunger', 'Lunar Voice'],
  shadowhunter: ['Demonic Impulse', 'Perfect Suppression'],
  souleater: ['Full Moon Harvester', "Night's Edge"],
  aeromancer: ['Drizzle', 'Wind Fury'],
  artist: ['Full Bloom', 'Recurrence'],
}
