export const CLASS_ENGRAVINGS = {
  berserker: ["Berserker's Technique", 'Mayhem'],
  destroyer: ['Gravity Training', 'Rage Hammer'],
  gunlancer: ['Combat Readiness', 'Lone Knight'],
  paladin: ['Blessed Aura', 'Judgment'],
  slayer: ['Predator', 'Punisher'],
  arcanist: ["Empress's Grace", 'Order of the Emperor'],
  bard: ['Desperate Salvation', 'True Courage'],
  sorceress: ['Igniter', 'Reflux'],
  summoner: ['Master Summoner', 'Communication Overflow'],
  glaivier: ['Pinnacle', 'Control'],
  scrapper: ['Ultimate Skill: Taijutsu', 'Shock Training'],
  soulfist: ['Energy Overflow', 'Robust Spirit'],
  wardancer: ['Esoteric Skill', 'First Intention'],
  striker: ['Esoteric Flurry', 'Deathblow'],
  breaker: ["Asura's Path", 'Brawl King Storm'],
  artillerist: ['Barrage Enhancement', 'Firepower Enhancement'],
  deadeye: ['Enhanced Weapon', 'Pistoleer'],
  gunslinger: ['Peacemaker', 'Time to Hunt'],
  machinist: ['Arthetinean Skill', 'Evolutionary Legacy'],
  sharpshooter: ['Loyal Companion', 'Death Strike'],
  deathblade: ['Surge', 'Remaining Energy'],
  reaper: ['Hunger', 'Lunar Voice'],
  shadowhunter: ['Demonic Impulse', 'Perfect Suppression'],
  souleater: ['Full Moon Harvester', "Night's Edge"],
  aeromancer: ['Drizzle', 'Wind Fury'],
  artist: ['Full Bloom', 'Recurrence'],
}

export const COMBAT_ENGRAVINGS = [
  'Adrenaline',
  'All-Out Attack',
  'Ambush Master',
  'Awakening',
  'Barricade',
  'Broken Bone',
  'Contender',
  'Crisis Evasion',
  'Crushing Fist',
  'Cursed Doll',
  'Disrespect',
  'Divine Protection',
  'Drops of Ether',
  'Emergency Rescue',
  'Enhanced Shield',
  'Ether Predator',
  'Expert',
  'Explosive Expert',
  'Fortitude',
  'Grudge',
  'Heavy Armor',
  'Hit Master',
  'Keen Blunt Weapon',
  'Lightning Fury',
  'Magick Stream',
  'Mass Increase',
  'Master Brawler',
  'Master of Escape',
  "Master's Tenacity",
  'Max MP Increase',
  'MP Efficiency Increase',
  'Necromancy',
  'Precise Dagger',
  'Preemptive Strike',
  'Propulsion',
  'Raid Captain',
  'Shield Piercing',
  'Sight Focus',
  'Spirit Absorption',
  'Stabilized Status',
  'Strong Will',
  'Super Charge',
  'Vital Point Hit',
] as const
