/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChangelogIndexImport } from './routes/changelog/index'

// Create Virtual Routes

const RosterIndexLazyImport = createFileRoute('/roster/')()
const PartiesIndexLazyImport = createFileRoute('/parties/')()
const FriendsIndexLazyImport = createFileRoute('/friends/')()
const RosterIdLazyImport = createFileRoute('/roster/$id')()
const PartiesIdLazyImport = createFileRoute('/parties/$id')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RosterIndexLazyRoute = RosterIndexLazyImport.update({
  path: '/roster/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/roster/index.lazy').then((d) => d.Route))

const PartiesIndexLazyRoute = PartiesIndexLazyImport.update({
  path: '/parties/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/parties/index.lazy').then((d) => d.Route))

const FriendsIndexLazyRoute = FriendsIndexLazyImport.update({
  path: '/friends/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/friends/index.lazy').then((d) => d.Route))

const ChangelogIndexRoute = ChangelogIndexImport.update({
  path: '/changelog/',
  getParentRoute: () => rootRoute,
} as any)

const RosterIdLazyRoute = RosterIdLazyImport.update({
  path: '/roster/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/roster/$id.lazy').then((d) => d.Route))

const PartiesIdLazyRoute = PartiesIdLazyImport.update({
  path: '/parties/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/parties/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/parties/$id': {
      preLoaderRoute: typeof PartiesIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/roster/$id': {
      preLoaderRoute: typeof RosterIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/changelog/': {
      preLoaderRoute: typeof ChangelogIndexImport
      parentRoute: typeof rootRoute
    }
    '/friends/': {
      preLoaderRoute: typeof FriendsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/parties/': {
      preLoaderRoute: typeof PartiesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/roster/': {
      preLoaderRoute: typeof RosterIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PartiesIdLazyRoute,
  RosterIdLazyRoute,
  ChangelogIndexRoute,
  FriendsIndexLazyRoute,
  PartiesIndexLazyRoute,
  RosterIndexLazyRoute,
])

/* prettier-ignore-end */
